/* Database schema to keep the structure of entire database. */

/* Create table animals */
CREATE TABLE ANIMALS(
 id int GENERATED BY DEFAULT AS IDENTITY,
 name varchar(100) NOT NULL,
 date_of_birth date,
 escape_attempts int NOT NULL,
 neutered boolean NOT NULL,
 weight_kg decimal NOT NULL
);

/* Alter the animals table */
ALTER TABLE animals ADD COLUMN species varchar(100);

/* Create table owners */
CREATE TABLE owners (
 id SERIAL PRIMARY KEY,
 full_name varchar(100) NOT NULL,
 age int NOT NULL);

/* Create table species */
CREATE TABLE species (
 id SERIAL PRIMARY KEY,
 name varchar(100) NOT NULL);

/* Alter table animals */

/* Open transaction */
BEGIN;

/* Remove column species */
ALTER TABLE animals DROP COLUMN species;

/* Add column species_id which is a foreign key referencing species table*/
ALTER TABLE animals
  ADD COLUMN species_id int,
  ADD CONSTRAINT fk_animals_species
    FOREIGN KEY (species_id)
    REFERENCES species (id);

/* Add column owner_id which is a foreign key referencing the owners table */
ALTER  TABLE animals ADD COLUMN owner_id int,
  ADD CONSTRAINT fk_animals_owners
    FOREIGN KEY(owner_id)
    REFERENCES owners(id);

/* Commit transaction */
COMMIT;
